### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by Naesstrom** [psvanstrom/esphome-p1reader#14]
So I got inspired with the new energy dashboard, found this repo when searching for alternatives to the dutch P1 system.

Redid your schematic to use a wemos d1 mini instead
![image](https://user-images.githubusercontent.com/6575206/128479880-2898685f-6b3a-4ed4-a04e-0113c6a38bc4.png)

And ofc a matching PCB
![image](https://user-images.githubusercontent.com/6575206/128480009-2a23326c-cdae-49dd-9f37-a994a2232466.png)

PCB is open for anyone to copy, download etc. here https://oshwlab.com/Naesstrom/esphome-p1reader

Now I just need to wait for the PCB's to design the 3d printed case :D

**Comment by psvanstrom** [comment]
This is awesome @Naesstrom! Can I incorporate your PCB image and the link to the PCB into the README.md of this project?

**Comment by Naesstrom** [comment]
absolutely @psvanstrom, I can update you once I get the PCB's to. I ordered a bunch so I can send you one!

**Comment by psvanstrom** [comment]
Thanks @Naesstrom! I updated the README with your PCB design. I would love to try out the PCB once you get it delivered 🙏

**Comment by TobbeWendt** [comment]
@Naesstrom  I am interested to by 1-2 boards from you if possible. I live in Sweden.

**Comment by Naesstrom** [comment]
Got them today but the 6/6 contacts from electrokit that I had didn't fit. If you have ordered from somewhere else they might fit tough!
This are the ones that didn't fit: https://www.electrokit.com/en/product/modular-connector-6-6-pcb/
This is the model I used: https://lcsc.com/product-detail/Ethernet-Connectors-Modular-Connectors-RJ45-RJ11_CONNFLY-Elec-DS1133-S60APS_C77857.html

So either I have to source a new 6/6 contact or order new pcbs

**Comment by Naesstrom** [comment]
![p1_box](https://user-images.githubusercontent.com/6575206/132738524-8405c8de-a580-450c-9847-2f41eaa0ef68.jpg)
Uploaded the STL's for the box here. Tight fit but looks nice!
https://www.thingiverse.com/thing:4961372

**Comment by psvanstrom** [comment]
Awesome, I'll add it to the README 👍

**Comment by SchneHa** [comment]
R1 and R2 has to be changed
The PCB should be improved by inserting a electrolytic cap of at least 1000µF/16V between 5V and GND and a jumper to cut RX to make it easy flashable if built in enclosure
The thing files of the enclosure doesn't have a lid for the large version that fits. It seems to be molded with the enclosure itself to get a totally closed enclosure.

**Comment by SchneHa** [comment]
Regarding the thing files:
Here you can find files for a well fitting enclosure with lid: https://www.thingiverse.com/thing:5564796

The PCB still needs an improvement.

**Comment by cenobitedk** [comment]
@Naesstrom Do you have any extra PCB you're selling?

**Comment by SchneHa** [comment]
Hello Jeppe,sure, but at the moment I‘m not at home for the next 3 weeks.Do you need the PCB only but also other parts?Best regards,HansAm 07.04.2024 um 10:51 schrieb Jeppe Hasseriis ***@***.***>:﻿
@Naesstrom Do you have any extra PCB you're selling?

**Comment by cenobitedk** [comment]
@SchneHa Cool, I need the PCB and the 6P6 connecter if you have it? I have loads of resistors etc. already. Thanks

**Comment by SchneHa** [comment]
Sure, and I think you need the capacitor as well as it has to fit between the connectors.Where are you?Am 07.04.2024 um 11:11 schrieb Jeppe Hasseriis ***@***.***>:﻿
@SchneHa Cool, I need the PCB and the 6P6 connecter if you have it? I have loads of resistors etc. already. Thanks

**Comment by SchneHa** [comment]
I think it was a misunderstanding. I‘m talking about this device: github.comAm 07.04.2024 um 12:55 schrieb Hans Schneider ***@***.***>:﻿Sure, and I think you need the capacitor as well as it has to fit between the connectors.Where are you?Am 07.04.2024 um 11:11 schrieb Jeppe Hasseriis ***@***.***>:﻿
@SchneHa Cool, I need the PCB and the 6P6 connecter if you have it? I have loads of resistors etc. already. Thanks

**Comment by cenobitedk** [comment]
Not sure what you are linking to, I only see "github.com" and no link.

**Comment by SchneHa** [comment]
Sorry, chopped by mistake: https://github.com/SchneHa/P1-WiFi-Gateway

**Comment by cenobitedk** [comment]
Ah, yeah, ok, that's not what I'm looking for :) thanks anyway
