### ISSUE TITLE
Wiring diagram for esp32 processor

### ISSUE THREAD

**Issue by mnil** [psvanstrom/esphome-p1reader#25]
Hello, is it possible to add a wiring diagram for esp32 processors, for example the `adafruit feather`?
https://www.adafruit.com/product/3405
I can't seem to understand the esp8266 diagram enough to make them valid for esp32.

**Comment by Schonke** [comment]
The Huzzah32 labels the 5V/VIN line as "USB" on the board. You should be able to take the NodeMCU wiring diagram and just replace VIN with USB and it should work.

**Comment by psvanstrom** [comment]
As @Schonke writes above: USB = 5V: https://learn.adafruit.com/adafruit-huzzah32-esp32-feather/pinouts
