### ISSUE TITLE
Add mqtt support

### ISSUE THREAD

**Issue by calania** [psvanstrom/esphome-p1reader#30]
Hello! Would it be possible to add mqtt support for us that use something other than home assist?

**Comment by psvanstrom** [comment]
ESPHome has an extensive support for MQTT so it is absolutely possible to configure the p1-reader to publish MQTT events instead of using the Home Assistant API. This would not require any changes to the code, only configuration changes in the yaml file: https://esphome.io/components/mqtt.html

**Comment by calania** [comment]
Sounds awesome! Will have a look.

**Comment by ulfwin** [comment]
@calania Please let us know your findings! I'm using openhab so I'm also very interested in this 😁

**Comment by calania** [comment]
@ulfwin Sadly I haven't received my meter yet but I will report back once I get it!
