### ISSUE TITLE
P1 Decryption key for Luxembourgish Meters 

### ISSUE THREAD

**Issue by koosoli** [psvanstrom/esphome-p1reader#41]
Hi, 
where can I enter the P1 decryption key for Luxembourgish Meters?
In WeiGus Code it is writen like so: 
//Key for SAG1030700089067 
uint8_t KEY_SMARTY[] = {0xAE, 0xBD, 0x21, 0xB7, 0x69, 0xA6, 0xD1, 0x3C, 0x0D, 0xF0, 0x64, 0xE3, 0x83, 0x68, 0x2E, 0xFF};

sorry, I am a beginner in all of this.

Thank you

**Comment by psvanstrom** [comment]
Hi, this software is designed only for the Swedish, unencrypted version of the P1 protocol, so it doesn't support the encrypted format used in Luxembourg unfortunately. But the built in DSMR module in ESPHome support it out of the box, check here: https://esphome.io/components/sensor/dsmr.html
