### ISSUE TITLE
dual tariff

### ISSUE THREAD

**Issue by pathia** [psvanstrom/esphome-p1reader#77]
Hello,

Here in the Netherlands we can have a dual tariff subscription in which we have a peak and off peak tariff.
Can this code handle that and have 2 different sensors for both import and export  (meaning 4 in total)

**Comment by cadwal** [comment]
Not without changes since the purpose of it is to handle the specific selection of data points used in Sweden (and a few other countries).

For the Netherlands you should be able to use the default builtin support in esphome.

https://esphome.io/components/sensor/dsmr.html

**Comment by pathia** [comment]
Thanks. Will try that 👍
